### ISSUE TITLE
WQ-50_BASEPLATE.stp file not found

### ISSUE THREAD

**Issue by benjaminmisiuk** [UNCG-DAISY/SandCam#149]
The .stp that is linked in the 1. Build Camera (v3) [page ](https://github.com/UNCG-DAISY/Instagrain/wiki/1.-Build-Camera-(v3)) for the WQ-50_BASEPLATE gives a "404 - page not found".

**Comment by ebgoldstein** [comment]
hi @benjaminmisiuk - thx for noticing this... I have now corrected the link in the wiki for the v3 baseplate... here is the direct link if you need it: 

https://github.com/UNCG-DAISY/Instagrain/blob/main/hardware/V3/WQ-50P_BASEPLATE.stp

**Comment by ebgoldstein** [comment]
(and I'm happy to discuss the camera if you are interested, LMK...)
