### ISSUE TITLE
Hardware Build instructions

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SandCam#40]
In the readme (or the readme of '/hardware/' ) we need a step-by-step set of instructions (w/ pictures) to show how to assemble & build the camera.

**Comment by ebgoldstein** [comment]
all parts are here except base-plates.
- [ ] ship parts and print materials
- [ ] order baseplate
- [ ] ship baseplate

once these are done, we need:
-  to assemble the cameras (I m listing it here since i closed #55),
- document the assembly for the readme of `/hardware/`

**Comment by jacobstasiewicz** [comment]
Hardware build instructions are done! finished yesterday
