### ISSUE TITLE
US GPS/GNSS board supplier

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SandCam#42]
@jacobstasiewicz , is this the exact same board you used?

https://www.amazon.com/BerryGPS-IMUv3-Raspberry-Accelerometer-Magnetometer-Barometric/dp/B072MNBC9M

if so, i will replace the link in the BOM.md file...

**Comment by jacobstasiewicz** [comment]
I know nothing about gps positioning but this one is cheaper, https://www.amazon.com/Raspberry-Pi-Multi-GNSS-Interface-Industrial/dp/B07QBF7F45/ref=sr_1_11?dchild=1&keywords=raspberry+pi+gps&qid=1634578559&sr=8-11, maybe tomorrow you could give me a quick crash course in gps systems
