### ISSUE TITLE
Low voltage warning

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SandCam#43]
The current battery pack gives a `Low Voltage` warning on the Pi... we need to find a battery pack that will run the pi at the required voltage.

**Comment by jacobstasiewicz** [comment]
https://www.adafruit.com/product/3859?gclid=Cj0KCQiAip-PBhDVARIsAPP2xc2y_RCiG9sw8f2Fa9_joiUgRGPwFoazdhbC2erq6x8Je2QxGLaqU-YaAlUxEALw_wcB
