### ISSUE TITLE
TF Lite code On device

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SandCam#47]
put the model on the device and embed within the RPi code 

(replaces #16 )

**Comment by ebgoldstein** [comment]
done, via https://github.com/UNCG-DAISY/SandCam/commit/2fd696d75cc0b611c9917e99a5e793dae3e84fd5

note that pip install of tflite is still needed on actual camera.. se above for link how to do it

**Comment by ebgoldstein** [comment]
and fyi, w/16 bit quant model, an inference takes ~ 4 seconds...

**Comment by jacobstasiewicz** [comment]
NO ML on device

**Comment by jacobstasiewicz** [comment]
Sike I lied, ML is on the device !!!!!
