### ISSUE TITLE
fritzing

### ISSUE THREAD

**Issue by jacobstasiewicz** [UNCG-DAISY/SandCam#53]
update fritzing diagram to V2

**Comment by jacobstasiewicz** [comment]
Diagram updated to v2, now I need to add the Ultimate GPS hat Diagram

**Comment by ebgoldstein** [comment]
closed via https://github.com/UNCG-DAISY/SandCam/commit/a332dccd42a25e41c2f2b9f5cefe54fcd4dedacc
