### ISSUE TITLE
Improve info in csv header

### ISSUE THREAD

**Issue by RyanMieras** [UNCG-DAISY/SandCam#56]
https://github.com/UNCG-DAISY/SandCam/blob/2fd696d75cc0b611c9917e99a5e793dae3e84fd5/software/photosieve.py#L50

Please include more detailed information about the units in the header, and use more descriptive header names

For example, 

Filename, Date (UTC), Latitude (DD), Latitude (DD), Altitude (m), D_5 (mm), D_10 (mm), . . . . . ETC . . . . D_95 (mm), Standard Deviation (UNITS), Skewness (UNITS), Kurtosis (UNITS)

- [ ] std dev, skewness, and kurtosis all have units! list the units, please! 
- [ ] grain size bins need units 
- [ ] Also, what is the altitude relative to? is it the ellipsoid height? orthometric? 
- [ ] And what is the lat/long system? WGS84? 
- [ ] And is it decimal degrees? or Degrees, minutes, seconds? if it's decimal degrees, for example, you should put "Latitude (DD)" or for degrees, minutes, seconds, you could put "Latitude (DMS)"

**Comment by jacobstasiewicz** [comment]
Fixed the Headers to reflect suggestion
