### ISSUE TITLE
Swappable camera tents

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SandCam#63]
Modify the case so that the camera 'tent' can be swapped to different (i.e., longer/shorted)..
This means the camera and ring light are attached to the camera body

**Comment by ebgoldstein** [comment]
Peg system has been incorporated into the model by @jacobstasiewicz . Additionally the tent system has screws attaching tot eh body, just in case the pegs do not work. @jacobstasiewicz , please close this when the new tent and new polycase CNC files are uploaded.

**Comment by jacobstasiewicz** [comment]
All files are uploaded
