### ISSUE TITLE
Add place to mount Coral usb accelerator

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SandCam#67]
since it works and speeds prediction... (i.e., https://github.com/UNCG-DAISY/SandCam/discussions/61)
could go inside or outside..

**Comment by jacobstasiewicz** [comment]
New case designed to have mount points inside and outside, will test and see if inside gets to hot. This is issue can be closed when testing is done

**Comment by ebgoldstein** [comment]
i propose we close this for now, since the mounting points are incorporated.. @jacobstasiewicz if you want to open a new issue for testing temps inside the case, then go for it.
