### ISSUE TITLE
Fix Mcmaster-Carr cart to reflect case v2

### ISSUE THREAD

**Issue by jacobstasiewicz** [UNCG-DAISY/SandCam#83]
M3 screws in current cart have a pitch of 0.35mm, and it should be 0.45mm (Screen Bracket)

M2.5 Standoffs for LED Bracket need to be 15mm not 10mm

**Comment by ebgoldstein** [comment]
(also do we need washers and longer bolts for the handles?)

when you update all these parts do you want me to buy them, or will the current parts work?

**Comment by jacobstasiewicz** [comment]
Mcmaster carr cart is up to date
