### ISSUE TITLE
Focusing Jig

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SandCam#87]
Focusing the camera is super hard - with the aperture, back-focus screw, light strength, and the normal focusing ring.

a 3D printed jig would be helpful

initial design looks like this:
<img src="https://user-images.githubusercontent.com/5330599/170703200-1e0d938c-4c2a-48d5-a113-89715f8427e8.png" width="200" />

**Comment by ebgoldstein** [comment]
stl file : https://github.com/UNCG-DAISY/SandCam/commit/b451561ca99871739699a5ee7c5fff1f92ebd56e

**Comment by jacobstasiewicz** [comment]
updated and fixed design
