### ISSUE TITLE
PDF of grain size

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SandCam#90]
it might be helpful to display a PDF of the grain size, and not just the CDF. (this suggestion is from @ncohn).

I am not sure how to display it graphically (if they should be on the same plot panel? or with a button? or two panels?)

here is a code snippet for the needed steps w/ `scipy.misc.derivative`:

https://datascience.oneoffcoder.com/pdf-cdf.html

**Comment by jacobstasiewicz** [comment]
evan I think it would be easiest to make the entire plot a button, so when clicked it will switch between the two types

**Comment by ebgoldstein** [comment]
Good idea

**Comment by ebgoldstein** [comment]
@jacobstasiewicz - give this a test on the device. There was no plot showing when i tried it this morning on my device

**Comment by jacobstasiewicz** [comment]
give it a try now

**Comment by ebgoldstein** [comment]
works - super nice!.. the code also seems faster to me!

**Comment by jacobstasiewicz** [comment]
Thanks! Is there a way to quantify the speed of the code? I would like to run a test and make a base line so when we are streamlining the code I can see what methods work best, just out of curiosity

**Comment by ebgoldstein** [comment]
i made a new issue for that..
